version: '2'
services:
  jenkins-server:
    build: .
    image: icr-docker-00.registry.com:5000/jenkins:1.0.0
    restart: unless-stopped
    hostname: jenkins-server
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JENKINS_SLAVE_AGENT_PORT=50000
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_log:/var/log/jenkins
volumes:
  jenkins_home:
  jenkins_log:
